name: tribe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Εικονίδια για iOS
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  
  # Πακέτα Χάρτη (τα αφήνω αφού τα είχες)
  
  # Firebase (Οι εκδόσεις που είχες)
  firebase_core: ^3.8.1
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.1.0
  firebase_storage: ^12.1.0
  shared_preferences: ^2.2.0
  
  # Image Picker για φωτογραφίες προφίλ
  image_picker: ^1.0.4
  google_maps_flutter: ^2.14.0
  geocoding: ^4.0.0
  flutter_local_notifications: ^18.0.1
  
  # HTTP client for API requests

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/user_icon.png"
  adaptive_icon_background: "#1877F2"
  adaptive_icon_foreground: "assets/images/user_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/